version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '4444:4444'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    env_file:
      - .env

volumes:
  data:
  node_modules:
